import type { Translator } from "../i18n/translate";
import type { ChatEntry } from "../state/useChat";
import { coverageLine } from "./coverage";
import { formatDuration } from "./duration";
import { localiseInternalNames } from "./displayNames";
import { counted } from "./plural";
import { formatTabularAnswer } from "./tabularAnswer";

/**
 * Everything written under an answer, as plain lines: where it came from, what it rests on, what could
 * not be established, what the engine corrected. One function, used by the conversation view and by
 * "Copy the conversation", so that what she copies is what she saw (HAP-1, lot D replay: the copy left
 * out the engine's sub-answers and the notes under each answer).
 *
 * The lists of sources (documents, sheets) are not here: they are references, shown as their own
 * disclosure and left out of a copy on purpose.
 */
export function annotationLines(t: Translator, locale: string, entry: ChatEntry): string[] {
  const lines: string[] = [];
  const coverage = entry.coverage === undefined ? null : coverageLine(t, entry.coverage);
  // How much of the folder this answer rests on, for a question that asked about every document.
  // Written beside the answer rather than inside it, so the model cannot leave it out.
  if (coverage !== null) {
    lines.push(coverage);
  }
  // She selected no document, so the model wrote this from general knowledge.
  if (entry.withoutDocuments === true) {
    lines.push(t("chat.withoutDocuments"));
  }
  // Documents the answer could not have used (never analysed, or changed since).
  if (entry.unanalysedFiles !== undefined) {
    lines.push(
      t("chat.unanalysed", {
        documents: counted(entry.unanalysedFiles, t("chat.unanalysedOne"), t("chat.unanalysedMany")),
      }),
    );
  }
  // Files she chose that are gone or have changed: the answer was written without them.
  if (entry.scopeOutdated !== undefined) {
    lines.push(
      t("chat.scopeOutdated", {
        files: counted(entry.scopeOutdated.length, t("chat.scopeFileOne"), t("chat.scopeFileMany")),
      }),
    );
  }
  // An answer she stopped has no duration to report: this takes the place of the line below.
  if (entry.interrupted !== undefined) {
    lines.push(t(entry.interrupted === "timedOut" ? "chat.timedOut" : "chat.interrupted"));
  }
  if (entry.durationMs !== undefined && entry.modelAlias !== undefined) {
    lines.push(
      t("chat.generatedBy", { model: entry.modelAlias, duration: formatDuration(entry.durationMs) }),
    );
  }
  // Where the "generated by" line would be, for an answer no model wrote. A table answer, alone or in
  // a mixed question, names the data folder; a folder answer names the documents folder.
  if (entry.deterministic === true) {
    lines.push(
      t(entry.tabular === true || entry.mixed === true ? "chat.deterministicData" : "chat.deterministic"),
    );
  }
  // Documents and tables were both selected, and the question was only about the data.
  if (entry.documentsNotNeeded === true) {
    lines.push(t("chat.documentsNotNeeded"));
  }
  // The mixed tier's own partial-refusal lines: which side could not be established.
  if (entry.mixedTableUnavailable !== undefined) {
    lines.push(t(`chat.mixedTableUnavailable.${entry.mixedTableUnavailable}`));
  }
  if (entry.mixedDocumentsUnavailable !== undefined) {
    lines.push(t(`chat.mixedDocumentsUnavailable.${entry.mixedDocumentsUnavailable}`));
  }
  // Appended, never silent: the model's draft stays as written, and every number it wrote that did not
  // match the table or an excerpt is corrected here instead.
  for (const correction of entry.mixedCorrections ?? []) {
    lines.push(
      t("chat.mixedCorrection", {
        claimed: correction.claimed,
        correct: new Intl.NumberFormat(locale, { maximumFractionDigits: 6 }).format(correction.correct),
      }),
    );
  }
  for (const citation of entry.mixedRejectedCitations ?? []) {
    lines.push(t("chat.mixedRejectedCitation", { citation }));
  }
  // A real, failed attempt to interpret the question with a model still cost real time.
  if (entry.modelAttemptAlias !== undefined && entry.modelAttemptDurationMs !== undefined) {
    lines.push(
      t(entry.modelAttemptKept === true ? "chat.modelAttemptedKept" : "chat.modelAttempted", {
        model: entry.modelAttemptAlias,
        duration: formatDuration(entry.modelAttemptDurationMs),
      }),
    );
  }
  // A figure the model stated that is in none of the excerpts it was given and not in the question.
  for (const number of entry.unverifiedNumbers ?? []) {
    lines.push(t("chat.unverifiedNumber", { number }));
  }
  return lines;
}

/** The engine's own figure in a mixed answer, as shown beside the model's prose: a title and the
 * sentence the engine would have given alone, with the filters it was computed under. `null` when
 * there is none, or when that sentence already is the whole answer. */
export function computedBlock(t: Translator, locale: string, entry: ChatEntry): string | null {
  if (entry.mixedTable?.kind !== "value" || entry.deterministic === true) {
    return null;
  }
  return [t("chat.mixedComputedTitle"), "", formatTabularAnswer(t, entry.mixedTable, locale)].join("\n");
}

/** What "Copy the conversation" puts on the clipboard for one answer: the text as shown (internal
 * names replaced), the engine's block, then the notes under it. Sources are left out. */
export function answerForCopy(t: Translator, locale: string, entry: ChatEntry): string {
  const parts = [localiseInternalNames(entry.content, t)];
  const computed = computedBlock(t, locale, entry);
  if (computed !== null) {
    parts.push(computed);
  }
  const notes = annotationLines(t, locale, entry);
  if (notes.length > 0) {
    parts.push(notes.join("\n"));
  }
  return parts.join("\n\n");
}
