import { describe, expect, it } from "vitest";
import { CATALOGUES, REFERENCE_LOCALE } from "../i18n/catalogues";
import { createTranslator, type Catalogue } from "../i18n/translate";
import type { TabularAnswer, TabularRow } from "./ipc";
import {
  formatTabularAnswer,
  MAX_ROWS_SHOWN,
  tabularSourceLine,
  tabularSourceOf,
} from "./tabularAnswer";

/**
 * The sentence for an answer the tabular engine gave. Facts and machine codes in, her language
 * out, and never a sheet, column or value the engine did not return.
 */

const reference = CATALOGUES[REFERENCE_LOCALE] as Catalogue;
const english = createTranslator(reference, reference);
const french = createTranslator(CATALOGUES["fr-FR"] as Catalogue, reference);

function sum(value: number, unit: string | null = null, unparsed = 0): TabularAnswer {
  return {
    kind: "value",
    file: "factures.csv",
    value: { kind: "sum", value: { value, unit, unparsed } },
    locator: { sheet: "Facturation", headerRow: 0, column: "montant", rowRange: [0, 11], filters: [] },
    derivation: { kind: "computed", operation: "sum", row_count: 12 },
  };
}

const nudge: TabularAnswer = {
  kind: "nudge",
  file: "factures.csv",
  reason: null,
  availableSheets: ["factures"],
  availableColumns: ["nom", "montant", "date"],
  exampleColumn: "montant",
  exampleGroup: "nom",
  filterColumn: null,
  filterValue: null,
  closeValues: [],
  modelAttempt: null,
};

describe("a computed value", () => {
  it("is printed exactly, in the way her language writes numbers", () => {
    const text = formatTabularAnswer(french, sum(1234.5), "fr-FR");

    expect(text).toContain("montant");
    // French groups thousands with a narrow no-break space and uses a decimal comma.
    expect(text).toMatch(/1\s234,5/u);
    expect(text).toContain("12 lignes");
  });

  it("keeps every significant digit it was given", () => {
    expect(formatTabularAnswer(english, sum(0.125), "en-US")).toContain("0.125");
  });

  it("shows the unit beside the value, exactly as the column carried it", () => {
    expect(formatTabularAnswer(french, sum(1234.5, "€"), "fr-FR")).toMatch(/1\s234,5\s€/u);
    expect(formatTabularAnswer(english, sum(15, "%"), "en-US")).toContain("15 %");
  });

  it("says how many cells could not be read as numbers, only when some could not", () => {
    const clean = formatTabularAnswer(english, sum(100), "en-US");
    expect(clean).not.toContain("could not be read");

    const withUnparsed = formatTabularAnswer(english, sum(100, null, 3), "en-US");
    expect(withUnparsed).toContain("3 cells could not be read as numbers.");

    const oneUnparsed = formatTabularAnswer(french, sum(100, null, 1), "fr-FR");
    expect(oneUnparsed).toContain("1 cellule n'a pas pu être lue comme un nombre.");
  });
});

describe("a value computed from a model-interpreted plan (session 14)", () => {
  function interpreted(modelAlias: string): TabularAnswer {
    return {
      kind: "value",
      file: "factures.csv",
      value: { kind: "sum", value: { value: 450, unit: null, unparsed: 0 } },
      locator: { sheet: "factures", headerRow: 0, column: "montant", rowRange: [0, 8], filters: [] },
      derivation: {
        kind: "interpreted_by_model",
        operation: "sum",
        row_count: 9,
        model_alias: modelAlias,
        plan: { aggregate: { op: "sum", column: "montant" } },
      },
    };
  }

  it("carries an invitation to rephrase, distinct from an ordinary computed answer - but never the model's own name", () => {
    // Naming the model and timing it is `useChat.ts`'s job (the same "Generated by {model} in
    // {duration}" line every other model-touched answer gets, from `derivation.model_alias`
    // directly) - this function only has to add what that line cannot say on its own.
    const plain = formatTabularAnswer(english, sum(450), "en-US");
    const model = formatTabularAnswer(english, interpreted("cabinet-chat"), "en-US");

    expect(plain.toLowerCase()).not.toContain("rephrase");
    expect(model).not.toContain("cabinet-chat");
    expect(model.toLowerCase()).toContain("rephrase");
    // The value itself is still written exactly like an ordinary computed answer - the sentence is
    // additional, never a replacement for the engine's own number.
    expect(model).toContain("450");
  });

  it("writes the invitation in her language too", () => {
    const text = formatTabularAnswer(french, interpreted("cabinet-chat"), "fr-FR");
    expect(text.toLowerCase()).toContain("reformul");
  });
});

describe("the citation of a tabular answer", () => {
  it("names the sheet and the column, never a page", () => {
    const source = tabularSourceOf(sum(1));
    expect(source).not.toBeNull();

    for (const t of [english, french]) {
      const line = tabularSourceLine(t, source!);
      expect(line).toContain("factures.csv");
      expect(line).toContain("Facturation");
      expect(line).toContain("montant");
      expect(line.toLowerCase()).not.toContain("page");
    }
    expect(tabularSourceLine(french, source!)).toBe(
      "factures.csv, feuille Facturation, colonne montant",
    );
  });

  it("cites the sheet a structural fact was read from", () => {
    const source = tabularSourceOf({
      kind: "structural",
      file: "classeur.xlsx",
      answer: { kind: "row_count", sheet: "Stock", rows: 40 },
    });

    expect(source).toStrictEqual({ file: "classeur.xlsx", sheet: "Stock", column: null });
    expect(tabularSourceLine(french, source!)).toBe("classeur.xlsx, feuille Stock");
  });

  it("cites nothing for an answer that rests on no one sheet", () => {
    expect(tabularSourceOf(nudge)).toBeNull();
    expect(
      tabularSourceOf({
        kind: "structural",
        file: "classeur.xlsx",
        answer: { kind: "sheet_names", sheets: ["A", "B"] },
      }),
    ).toBeNull();
  });
});

describe("the nudge", () => {
  it("names the workbook's real columns and a concrete question built from one", () => {
    const text = formatTabularAnswer(french, nudge, "fr-FR");

    expect(text).toContain("factures.csv");
    expect(text).toContain("nom, montant, date");
    expect(text).toContain("somme de montant");
    expect(text).toContain("Quel(le) nom a le plus de montant");
    expect(text).not.toContain("not_recognised");
  });

  it("says why when the engine refused, in words, not as a code", () => {
    const text = formatTabularAnswer(
      english,
      { ...nudge, reason: "formula_cannot_be_verified" } as TabularAnswer,
      "en-US",
    );

    expect(text).toContain("formulas");
    expect(text).not.toContain("formula_cannot_be_verified");
    expect(text).toContain("nom, montant, date");
  });

  it("lists the sheets when no sheet could be settled", () => {
    const text = formatTabularAnswer(
      french,
      {
        ...nudge,
        reason: "ambiguous_sheet_name",
        availableSheets: ["Consultations", "Facturation"],
        availableColumns: [],
        exampleColumn: null,
        exampleGroup: null,
      } as TabularAnswer,
      "fr-FR",
    );

    expect(text).toContain("Consultations, Facturation");
    expect(text).not.toContain("Par exemple");
  });

  it("is more direct the second time in a row", () => {
    const first = formatTabularAnswer(english, nudge, "en-US");
    const second = formatTabularAnswer(english, nudge, "en-US", true);

    expect(second.startsWith(first)).toBe(true);
    expect(second).toContain("previous question");
  });

  it("names the filter it saw and the column it was found in, never a code", () => {
    const text = formatTabularAnswer(
      english,
      {
        ...nudge,
        reason: "filter_not_supported",
        filterColumn: "fournisseur",
        filterValue: "Alpha",
      } as TabularAnswer,
      "en-US",
    );

    expect(text).toContain("Alpha");
    expect(text).toContain("fournisseur");
    expect(text).not.toContain("filter_not_supported");
  });

  it("omits the column line when none was found", () => {
    const text = formatTabularAnswer(
      english,
      {
        ...nudge,
        reason: "filter_not_supported",
        filterColumn: null,
        filterValue: "2021",
      } as TabularAnswer,
      "en-US",
    );

    expect(text).toContain("2021");
    expect(text).not.toContain("was found in the");
  });
});

describe("refusals and choices", () => {
  it("says plainly that a red workbook could not be read as a table", () => {
    expect(
      formatTabularAnswer(french, { kind: "workbook_unreadable", file: "notes.csv" }, "fr-FR"),
    ).toContain("notes.csv n'a pas pu être lu comme un tableau");
  });

  it("asks which workbook, listing only the ones selected", () => {
    const text = formatTabularAnswer(
      english,
      { kind: "which_workbook", candidates: ["achats.csv", "ventes.csv"] },
      "en-US",
    );

    expect(text).toContain("- achats.csv");
    expect(text).toContain("- ventes.csv");
  });
});

describe("a sorted listing", () => {
  function row(index: number, name: string): TabularRow {
    return {
      rowIndex: index,
      cells: [
        { column: "nom", text: name },
        { column: "montant", text: String(index) },
      ],
    };
  }

  it("is a table, with a pipe in a cell kept inside its cell", () => {
    const text = formatTabularAnswer(
      english,
      {
        kind: "value",
        file: "f.csv",
        value: { kind: "rows", value: [row(0, "A|B")] },
        locator: { sheet: "f", headerRow: 0, column: "montant", rowRange: [0, 0], filters: [] },
        derivation: { kind: "computed", operation: "sort", row_count: 1 },
      },
      "en-US",
    );

    expect(text).toContain("| nom | montant |");
    expect(text).toContain("| A\\|B | 0 |");
  });

  it("shows the first rows and counts the rest", () => {
    const rows = Array.from({ length: MAX_ROWS_SHOWN + 3 }, (_, index) => row(index, `n${index}`));
    const text = formatTabularAnswer(
      french,
      {
        kind: "value",
        file: "f.csv",
        value: { kind: "rows", value: rows },
        locator: { sheet: "f", headerRow: 0, column: "montant", rowRange: [0, rows.length - 1], filters: [] },
        derivation: { kind: "computed", operation: "sort", row_count: rows.length },
      },
      "fr-FR",
    );

    expect(text).toContain(`| n${MAX_ROWS_SHOWN - 1} |`);
    expect(text).not.toContain(`| n${MAX_ROWS_SHOWN} |`);
    expect(text).toContain("3 autres lignes");
  });
});

describe("which group costs the most", () => {
  function largest(top: { group: string; sum: number }[]): TabularAnswer {
    return {
      kind: "value",
      file: "revenue_sub_agency.csv",
      value: { kind: "largest_group", value: { groupColumn: "agency", top, groupCount: 12 } },
      locator: { sheet: "revenue_sub_agency", headerRow: 0, column: "amount", rowRange: [0, 99], filters: [] },
      derivation: { kind: "computed", operation: "largest_group", row_count: 100 },
    };
  }

  it("names the leader and its total, says it is a total per group, and ranks the next ones", () => {
    const text = formatTabularAnswer(
      english,
      largest([
        { group: "Transit", sum: 8500.25 },
        { group: "Parks", sum: 2000.5 },
      ]),
      "en-US",
    );

    expect(text).toContain("Largest total amount by agency: **Transit**, with **8,500.25**.");
    expect(text).toContain("not the largest single row");
    expect(text).toContain("12 groups");
    expect(text).toContain("- Parks: 2,000.5");
    expect(text).toContain("100 rows");
  });

  it("calls a tie a tie rather than picking one", () => {
    const text = formatTabularAnswer(
      french,
      largest([
        { group: "Parks", sum: 10 },
        { group: "Water", sum: 10 },
        { group: "Health", sum: 3 },
      ]),
      "fr-FR",
    );

    expect(text).toContain("Égalité");
    expect(text).toContain("**Parks, Water**");
  });

  it("asks which column to add up, naming the candidates", () => {
    const text = formatTabularAnswer(
      french,
      { kind: "which_measure", file: "costs.csv", groupColumn: "agency", candidates: ["amount", "fee"] },
      "fr-FR",
    );

    expect(text).toContain("amount, fee");
    expect(text).toContain("« Quel(le) agency a le plus de amount ? »");
  });
});

describe("a mean or a median", () => {
  function mean(value: number): TabularAnswer {
    return {
      kind: "value",
      file: "rendez-vous.xlsx",
      value: { kind: "mean", value: { value, unit: null, unparsed: 0 } },
      locator: { sheet: "Planning", headerRow: 0, column: "duree_min", rowRange: [0, 39], filters: [] },
      derivation: { kind: "computed", operation: "mean", row_count: 40 },
    };
  }

  function median(value: number): TabularAnswer {
    return {
      kind: "value",
      file: "rendez-vous.xlsx",
      value: { kind: "median", value: { value, unit: null, unparsed: 0 } },
      locator: { sheet: "Planning", headerRow: 0, column: "duree_min", rowRange: [0, 39], filters: [] },
      derivation: { kind: "computed", operation: "median", row_count: 40 },
    };
  }

  it("is never labelled a total", () => {
    const text = formatTabularAnswer(english, mean(29.375), "en-US");

    expect(text).toContain("Average of duree_min");
    expect(text).toContain("29.375");
    expect(text).not.toContain("Sum of");
    expect(text).toContain("40 rows");
  });

  it("writes a median with its own sentence", () => {
    const text = formatTabularAnswer(french, median(22.5), "fr-FR");

    expect(text).toContain("Médiane de duree_min");
    expect(text).toContain("22,5");
  });
});

describe("which group costs the least", () => {
  function least(top: { group: string; sum: number }[]): TabularAnswer {
    return {
      kind: "value",
      file: "rendez-vous.xlsx",
      value: { kind: "least_group", value: { groupColumn: "salle", top, groupCount: 4 } },
      locator: { sheet: "Planning", headerRow: 0, column: "duree_min", rowRange: [0, 39], filters: [] },
      derivation: { kind: "computed", operation: "least_group", row_count: 40 },
    };
  }

  it("names the smallest total, says it is a total per group, and never the largest-group wording", () => {
    const text = formatTabularAnswer(
      english,
      least([
        { group: "Iris", sum: 225 },
        { group: "Cedre", sum: 250 },
      ]),
      "en-US",
    );

    expect(text).toContain("Smallest total duree_min by salle: **Iris**, with **225**.");
    expect(text).toContain("not the single smallest row");
    expect(text).not.toContain("Largest total");
    expect(text).not.toContain("not the largest single row");
    expect(text).toContain("4 groups");
    expect(text).toContain("- Cedre: 250");
  });

  it("calls a tie a tie rather than picking one", () => {
    const text = formatTabularAnswer(
      french,
      least([
        { group: "Iris", sum: 10 },
        { group: "Cedre", sum: 10 },
        { group: "Azur", sum: 50 },
      ]),
      "fr-FR",
    );

    expect(text).toContain("Égalité");
    expect(text).toContain("**Iris, Cedre**");
  });
});

describe("the top N groups", () => {
  function topGroups(
    top: { group: string; sum: number }[],
    requested: number,
    capped: boolean,
  ): TabularAnswer {
    return {
      kind: "value",
      file: "rendez-vous.xlsx",
      value: {
        kind: "top_groups",
        value: { groupColumn: "salle", top, groupCount: 4, requested, capped },
      },
      locator: { sheet: "Planning", headerRow: 0, column: "duree_min", rowRange: [0, 39], filters: [] },
      derivation: { kind: "computed", operation: "top_n", row_count: 40 },
    };
  }

  it("lists the requested groups, largest first", () => {
    const text = formatTabularAnswer(
      english,
      topGroups(
        [
          { group: "Azur", sum: 400 },
          { group: "Lotus", sum: 300 },
          { group: "Cedre", sum: 250 },
        ],
        3,
        false,
      ),
      "en-US",
    );

    expect(text).toContain("- Azur: 400");
    expect(text).toContain("- Lotus: 300");
    expect(text).toContain("- Cedre: 250");
    expect(text).not.toContain("capped");
  });

  it("says when a larger N was capped", () => {
    const text = formatTabularAnswer(
      french,
      topGroups(
        [
          { group: "Azur", sum: 400 },
          { group: "Lotus", sum: 300 },
          { group: "Cedre", sum: 250 },
          { group: "Iris", sum: 225 },
        ],
        80,
        true,
      ),
      "fr-FR",
    );

    expect(text).toContain("80");
    expect(text).toContain("limité à 50");
  });
});

describe("rows per group", () => {
  function countPerGroup(value: { group: string; count: number }[]): TabularAnswer {
    return {
      kind: "value",
      file: "rendez-vous.xlsx",
      value: { kind: "count_per_group", value },
      locator: { sheet: "Planning", headerRow: 0, column: "salle", rowRange: [0, 39], filters: [] },
      derivation: { kind: "computed", operation: "count_per_group", row_count: 40 },
    };
  }

  it("lists every group's row count, as the engine ordered them", () => {
    const text = formatTabularAnswer(
      english,
      countPerGroup([
        { group: "Azur", count: 20 },
        { group: "Cedre", count: 10 },
        { group: "Iris", count: 5 },
        { group: "Lotus", count: 5 },
      ]),
      "en-US",
    );

    expect(text).toContain("Number of rows per salle");
    expect(text).toContain("- Azur: 20");
    expect(text).toContain("- Lotus: 5");
  });

  it("counts the rest once more than fifty groups exist", () => {
    const groups = Array.from({ length: MAX_ROWS_SHOWN + 2 }, (_, index) => ({
      group: `Salle ${index}`,
      count: MAX_ROWS_SHOWN - index,
    }));
    const text = formatTabularAnswer(french, countPerGroup(groups), "fr-FR");

    expect(text).toContain(`Salle ${MAX_ROWS_SHOWN - 1}`);
    expect(text).not.toContain(`Salle ${MAX_ROWS_SHOWN}`);
    expect(text).toContain("2 autres groupes");
  });
});

describe("a list of a column's values", () => {
  it("lists every value, and counts what does not fit", () => {
    const values = Array.from({ length: 53 }, (_, index) => `Agency ${index}`);
    const text = formatTabularAnswer(
      english,
      {
        kind: "value",
        file: "revenue_sub_agency.csv",
        value: { kind: "distinct", value: values },
        locator: { sheet: "revenue_sub_agency", headerRow: 0, column: "agency", rowRange: [0, 99], filters: [] },
        derivation: { kind: "computed", operation: "distinct", row_count: 100 },
      },
      "en-US",
    );

    expect(text).toContain("The 53 values found in agency");
    expect(text).toContain("- Agency 0");
    expect(text).not.toContain("- Agency 50");
    expect(text).toContain("3 more values");
  });
});

describe("a filtered value over no row", () => {
  const empty: TabularAnswer = {
    kind: "value",
    file: "rdv.xlsx",
    value: { kind: "count", value: 0 },
    locator: {
      sheet: "rdv",
      headerRow: 0,
      column: null,
      rowRange: [0, 9],
      filters: [{ kind: "equals", column: "patient", value: "Martin A" }],
    },
    derivation: { kind: "computed", operation: "count", row_count: 0 },
  };

  it("says the selection is empty and points at the line that shows what was understood", () => {
    expect(formatTabularAnswer(english, empty, "en-US")).toContain("No row matches these criteria.");
    expect(formatTabularAnswer(french, empty, "fr-FR")).toContain("Aucune ligne ne correspond");
  });

  it("is silent when there is no filter, or when rows matched", () => {
    expect(formatTabularAnswer(english, sum(10), "en-US")).not.toContain("No row matches");
    const unfiltered: TabularAnswer = { ...empty, locator: { ...empty.locator, filters: [] } };
    expect(formatTabularAnswer(english, unfiltered, "en-US")).not.toContain("No row matches");
  });
});

describe("a threshold on a group's total", () => {
  const refused: TabularAnswer = {
    kind: "nudge",
    file: "factures.csv",
    reason: "group_threshold_not_supported",
    availableSheets: ["factures"],
    availableColumns: ["nom", "montant", "date"],
    exampleColumn: "montant",
    exampleGroup: "nom",
    filterColumn: null,
    filterValue: "5000",
    closeValues: [],
    modelAttempt: null,
  };

  it("is refused in plain words in both languages, never shown as a raw code", () => {
    const text = formatTabularAnswer(french, refused, "fr-FR");
    expect(text).toContain("seuil au total d'un groupe");
    expect(text).not.toContain("group_threshold_not_supported");
    expect(formatTabularAnswer(english, refused, "en-US")).toContain("compares a threshold to a group's total");
  });
});

describe("a refusal about a column's content", () => {
  it("names the column it refused, so a question that named two is not a mystery", () => {
    const refused: TabularAnswer = {
      ...nudge,
      reason: "non_numeric_column",
      filterColumn: "fournisseur",
    } as TabularAnswer;
    expect(formatTabularAnswer(french, refused, "fr-FR")).toContain("Colonne concernée : fournisseur.");
    expect(formatTabularAnswer(english, refused, "en-US")).toContain("Column concerned: fournisseur.");
  });
});

describe("a filter on one day", () => {
  it("is shown as a day, not as a range that starts and ends the same day", () => {
    const answer: TabularAnswer = {
      kind: "value",
      file: "f.csv",
      value: { kind: "count", value: 0 },
      locator: {
        sheet: "f",
        headerRow: 0,
        column: null,
        rowRange: [0, 7],
        filters: [{ kind: "date_range", column: "date", start: "2026-01-23", end: "2026-01-23" }],
      },
      derivation: { kind: "computed", operation: "count", row_count: 0 },
    };
    const text = formatTabularAnswer(french, answer, "fr-FR");
    expect(text).toContain("date = 2026-01-23");
    expect(text).not.toContain("entre 2026-01-23 et 2026-01-23");
  });
});
