import { useCallback, useRef, useState } from "react";
import { useTranslation } from "../i18n/I18nProvider";
import { normaliseError, type AppError } from "../lib/errors";
import {
  phaseAfterFirstText,
  stopOutcome,
  wasStopped,
  type GenerationPhase,
  type StopOutcome,
} from "../lib/generation";
import { formatFolderAnswer } from "../lib/folderAnswer";
import { conversationHistory } from "../lib/history";
import { formatTabularAnswer, tabularSourceOf, type TabularSource } from "../lib/tabularAnswer";
import {
  askWithSources,
  cancelChat,
  hasIndexedDocuments,
  type ChatTurn,
  type Evidence,
  type EvidenceCoverage,
  type CombinedScope,
  type FolderAnswer,
  type MixedPartUnavailable,
  type NumericCorrection,
  type TabularAnswer,
} from "../lib/ipc";
import { truncateForRegenerate, truncateForResend } from "../lib/turns";

/** Retrieval found nothing to answer from. Either the documents do not carry it, or none have
 * been analysed yet, and the two deserve different sentences. */
const INSUFFICIENT_EVIDENCE = "insufficient_evidence";

/** The AI went quiet for longer than the configured wait. The answer it had already written is
 * real text she may have been reading, so it is kept, exactly as a stop keeps it. */
const SERVER_TIMEOUT = "server_timeout";

/** Whether the local index holds anything at all. Fails open: a transient index error must not
 * turn a real failure into "analyse your documents first". */
function indexHasAnything(): Promise<boolean> {
  return hasIndexedDocuments().catch(() => true);
}

export interface ChatEntry extends ChatTurn {
  id: string;
  /** When the turn was written, by the workstation clock. Shown above a question so a long
   * conversation can be read back in order; it never leaves the webview. */
  createdAt: number;
  /** Present on an assistant answer that came from the local index, so it can cite file and page. */
  sources?: Evidence[];
  /** Present when the question asked about every document. Shown so an answer that covered six
   * of ten analysed files cannot read as though it had covered all ten
   * (`docs/WORK-FOLDER-INVENTORY.md`). */
  coverage?: EvidenceCoverage;
  /** Documents in the folder this answer could not have used, because they were never analysed
   * or have changed since. Present only when there were any: the quiet failure this guards
   * against is a document dropped in the folder, never analysed, and an answer that reads as
   * though it had been taken into account. */
  unanalysedFiles?: number;
  /** Files the conversation's scope named that were gone or changed, so the answer left them out.
   * Present only when there were any: a narrower answer must not read as the one she asked for. */
  scopeOutdated?: string[];
  /** This answer is not an answer: it is the software saying the documents have not been read
   * yet. Copying or regenerating it is meaningless, so the turn offers the one thing that would
   * change it instead. */
  needsIndexing?: true;
  /** The work folder answered this itself: read from the disk and the local index, with no model
   * involved. Said on screen, because an answer with no model behind it is a different kind of
   * answer and the absence of a "generated by" line is too quiet a way to say so. */
  deterministic?: true;
  /** No document was selected, so this answer rests on none of hers. Said under it, because an
   * answer written from general knowledge must never read as one drawn from her folder. */
  withoutDocuments?: true;
  /** The tabular engine answered this, from the selected tables: tier 2. Usually with no model at
   * all; since session 14, a question the classifier could not read may have asked a model to
   * interpret it first (`durationMs`/`modelAlias` are then set, never `deterministic`) - but the
   * engine still computed the number either way. */
  tabular?: true;
  /** A tabular answer the model might do something with: a classified, computed value (the model
   * can try its own reading instead) or a nudge (the model may be the one thing left to try).
   * Never set for a tabular answer that names a human choice instead (`which_measure`,
   * `which_column`, `which_workbook`...) or carries no data to interpret at all - asking the model
   * there would not be "a second opinion", it would be guessing where this product refuses to.
   * Found worth adding directly from a real wrong deterministic answer in a manual validation
   * pass (`docs/DECISIONS.md`, 1 October 2026): correct arithmetic is not the same as a correct
   * reading of the question, and she asked for a way to request a second opinion when she
   * suspects the two came apart. Drives the same regenerate control every other tier already
   * offers, relabelled "Demander a l'IA"/"Ask AI" exactly as it already is for a deterministic
   * folder answer. */
  tabularRetryable?: true;
  /** The workbook and sheet this answer came from: where a document answer lists its pages. */
  tabularSource?: TabularSource;
  /** The engine could not answer exactly and suggested what to ask instead. Remembered so a second
   * miss in a row can say so, and be more direct. */
  tabularNudge?: true;
  /** This answer stops mid-sentence, and why. Shown as such either way: an incomplete summary
   * that looks finished is the risk the disclaimer exists for. "stopped" is her own stop;
   * "timedOut" is the AI falling silent, and the two must not be confused - one was her
   * decision, the other was not. */
  interrupted?: "stopped" | "timedOut";
  /** How long the answer took to write, and which profile wrote it - shown so a slow machine is
   * visible rather than silently endured (`docs/HARDWARE.md`). */
  durationMs?: number;
  modelAlias?: string;
  /** Set only on a tabular nudge that followed a real, failed attempt to interpret the question
   * with a model (`tabularAnswer.modelAttempt`, session 14's hidden interpreter) - distinct from
   * `durationMs`/`modelAlias` above, which mean "this is what the model actually wrote". Found in
   * a manual validation pass (`docs/DECISIONS.md`, 1 October 2026): a small local model can spend
   * a minute or more failing to produce a usable plan, and that wait must not vanish into a bare
   * "without the AI" with nothing to show for it. */
  modelAttemptAlias?: string;
  modelAttemptDurationMs?: number;
  /** The attempt was on a question the engine had already computed: the computed answer stays. */
  modelAttemptKept?: true;
  /** Documents and tables were both selected, but this question was clearly and only about the
   * data, so the tabular engine answered it alone and the documents selected alongside it were
   * never read - no retrieval, no gateway call (`docs/SESSION-DATA-15-Mixed-Routing.md`). Said
   * under the answer, beside the ordinary "without the AI" line a tabular answer already gets. */
  documentsNotNeeded?: true;
  /** Documents and tables were both selected, and the mixed tier answered across both
   * (`docs/SESSION-DATA-16-Mixed-Tier.md`): the engines computed and cited, the model only wrote.
   * Present exactly when the question reached that tier. */
  mixed?: true;
  /** The table's own part of a mixed answer - a computed value, a structural fact, a
   * disambiguation, or a nudge, formatted the same way tier 2's own answers are. `undefined` when
   * the question had no data component at all (`mixedTableUnavailable` is then set instead). */
  mixedTable?: TabularAnswer;
  /** Where the table part came from: the workbook and sheet, for its own "based on" line beside
   * the document sources' one. */
  mixedTableSource?: TabularSource;
  mixedTableUnavailable?: MixedPartUnavailable;
  mixedDocumentsUnavailable?: MixedPartUnavailable;
  /** A number the model wrote that did not match the table or any excerpt - appended under the
   * answer, which is never rewritten. */
  mixedCorrections?: NumericCorrection[];
  /** A bracketed citation the model wrote that did not resolve to any supplied document excerpt. */
  mixedRejectedCitations?: string[];
}

export interface ChatState {
  entries: ChatEntry[];
  /** "thinking" until the first words of the answer arrive, "writing" afterwards. Every stop
   * affordance and the spinner read this, so they cannot disagree about what is happening. */
  phase: GenerationPhase;
  /** The answer being written right now, so the spinner and the stop under it appear on that one
   * answer rather than under every answer already in the conversation. */
  streamingId: string | null;
  error: AppError | null;
  send: (question: string) => Promise<void>;
  /** Edited-and-reposted question (docs/CHAT-UX-ASSESSMENT.md item 3). Truncates `entries` to
   * before `questionEntryId` and asks the edited text as a fresh turn - not a rewrite of the old
   * one. No version history is kept: truncate and replace, per the recorded decision. */
  resend: (questionEntryId: string, text: string) => Promise<void>;
  /** Regenerate (item 4). Drops the answer at `answerEntryId` and the question right before it,
   * then asks that same question again. Retrieval, embedding and the model all run afresh, so the
   * sources shown are this run's own rather than the previous run's. */
  regenerate: (answerEntryId: string) => Promise<void>;
  /** Close the error banner. A failure that has already happened should not keep taking up the
   * conversation until the next question succeeds. */
  dismissError: () => void;
  /** Stops the question being worked on. Returns the question's text when stopping abandoned it
   * altogether, so the composer can offer it again - a stop before any answer is a question to
   * rephrase far more often than one to forget. Returns null when an answer was already being
   * written, since that text stays on screen and the composer is left as she had it. */
  stop: () => string | null;
  /** Empty the conversation and start a fresh one. Temporary, until conversations can be saved and
   * listed: today the only way to a clean slate was restarting the whole application, which is
   * what this replaces. Refuses while a question is in flight - the caller should keep the control
   * disabled then, the same way the folder card disables Reset while indexing runs - so a clear
   * never has to reason about a request that is still streaming into a conversation that no
   * longer exists on screen. */
  clear: () => void;
}

/**
 * `onFailure` runs when a message could not be answered. The window uses it to re-ask the gateway
 * how it is, so a server that went down is reported by the indicator and not only by this banner.
 *
 * Every question takes one path, with the conversation so far (`docs/SELECTION-AND-MEMORY.md`):
 * retrieval inside the documents she selected, answered only from what the local index returns
 * (`docs/RETRIEVAL.md`), or, with none selected, an answer without documents that says so. A
 * documents folder is required: without one nothing is sent, and the composer says to choose one.
 */
export function useChat(
  onFailure?: () => void,
  hasWorkFolder = false,
  modelAlias?: string,
  /** Which files questions may draw on, from both folders. Left out, the whole documents folder
   * and no table. */
  scope?: CombinedScope,
): ChatState {
  const { t, locale } = useTranslation();
  const [entries, setEntries] = useState<ChatEntry[]>([]);
  const [phase, setPhase] = useState<GenerationPhase>("idle");
  const [streamingId, setStreamingId] = useState<string | null>(null);
  const [error, setError] = useState<AppError | null>(null);
  /** The question in flight, so stopping it can offer it back without reading it out of the list
   * that is about to lose it. */
  const asked = useRef("");
  /** What she asked a stop to leave behind, recorded when she clicked rather than worked out again
   * once the request has ended - by then the phase has moved on. Null means no stop was asked for. */
  const stopRequest = useRef<StopOutcome | null>(null);

  /**
   * The turn itself, shared by a fresh question, an edited repost and a regenerate: all three are
   * "append this question and its answer onto some prefix of the conversation", differing only in
   * what that prefix is. `baseEntries` is taken as a parameter rather than read from state so a
   * repost or regenerate can truncate first and send against the truncated list in the same tick -
   * the non-retrieval path below rebuilds its turns from it, and a stale `entries` closure would
   * resend the tail that was just cut.
   */
  const runTurn = useCallback(
    async (baseEntries: ChatEntry[], text: string, skipDeterministic = false) => {
      if (phase !== "idle" || !hasWorkFolder) {
        return;
      }
      const questionId = crypto.randomUUID();
      const answerId = crypto.randomUUID();
      const createdAt = Date.now();
      asked.current = text;
      stopRequest.current = null;
      setError(null);
      setPhase("thinking");
      setStreamingId(answerId);
      setEntries([
        ...baseEntries,
        { id: questionId, role: "user", content: text, createdAt },
        { id: answerId, role: "assistant", content: "", createdAt },
      ]);

      const onDelta = (delta: string) => {
        setPhase(phaseAfterFirstText);
        setEntries((current) =>
          current.map((entry) => {
            if (entry.id !== answerId) {
              return entry;
            }
            // Ollama's chat template often opens an answer with a leading space token; strip
            // one only from the very first piece of a fresh answer, never mid-stream, so a
            // legitimate space inside the text is never touched.
            const piece = entry.content.length === 0 ? delta.replace(/^ /, "") : delta;
            return { ...entry, content: entry.content + piece };
          }),
        );
      };
      /* Sources arrive on their own event, before the first word of the answer, because retrieval
         has already finished by then. An answer she interrupts therefore still cites the documents
         it was written from, which an answer left on screen has to do. */
      const onSources = (sources: Evidence[], coverage: EvidenceCoverage | null) => {
        setEntries((current) =>
          current.map((entry) =>
            entry.id === answerId
              ? { ...entry, sources, ...(coverage === null ? {} : { coverage }) }
              : entry,
          ),
        );
      };
      /* A question the work folder answered by itself: no model wrote this, so it arrives as
         facts and machine codes and the sentence is written here, in her language. There are no
         sources because nothing was retrieved - the filesystem is the evidence
         (`docs/WORK-FOLDER-INVENTORY.md`). */
      const onFolderAnswer = (folderAnswer: FolderAnswer) => {
        const text = formatFolderAnswer(t, folderAnswer);
        setEntries((current) =>
          current.map((entry) =>
            entry.id === answerId
              ? { ...entry, content: text, deterministic: true as const }
              : entry,
          ),
        );
      };
      /* What a stop before any answer leaves behind: nothing at all, question included, so the
         conversation returns to exactly what it was. */
      const discardTurn = () =>
        setEntries((current) =>
          current.filter((entry) => entry.id !== questionId && entry.id !== answerId),
        );
      const startedAt = performance.now();

      try {
        const result = await askWithSources(
          text,
          onDelta,
          onSources,
          onFolderAnswer,
          skipDeterministic,
          scope,
          // What the conversation was before this question - `baseEntries` rather than `entries`,
          // so a repost or a regenerate remembers the conversation it truncated to.
          conversationHistory(baseEntries),
        );
        const outdated = result.scopeOutdated.length > 0 ? result.scopeOutdated : undefined;
        if (result.mixedAnswer !== null) {
          /* Session 16: documents and tables both selected, answered across both
             (`docs/SESSION-DATA-16-Mixed-Tier.md`). `mixed.answer` already streamed in through
             `onDelta`/`onSources` above when generation happened - the content set here is only
             for the degraded case, where no model was asked at all and the table's own value (or
             disambiguation) is the whole answer, formatted the same way tier 2's own is. */
          const mixed = result.mixedAnswer;
          const source = mixed.table === null ? null : tabularSourceOf(mixed.table);
          setEntries((current) =>
            current.map((entry) =>
              entry.id === answerId
                ? {
                    ...entry,
                    ...(mixed.answer === "" && mixed.table !== null
                      ? {
                          content: formatTabularAnswer(t, mixed.table, locale),
                          deterministic: true as const,
                        }
                      : { durationMs: performance.now() - startedAt, modelAlias }),
                    ...(outdated === undefined ? {} : { scopeOutdated: outdated }),
                    mixed: true as const,
                    ...(mixed.table === null ? {} : { mixedTable: mixed.table }),
                    ...(source === null ? {} : { mixedTableSource: source }),
                    ...(mixed.tableUnavailable === null
                      ? {}
                      : { mixedTableUnavailable: mixed.tableUnavailable }),
                    ...(mixed.documentsUnavailable === null
                      ? {}
                      : { mixedDocumentsUnavailable: mixed.documentsUnavailable }),
                    ...(mixed.corrections.length > 0 ? { mixedCorrections: mixed.corrections } : {}),
                    ...(mixed.rejectedCitations.length > 0
                      ? { mixedRejectedCitations: mixed.rejectedCitations }
                      : {}),
                  }
                : entry,
            ),
          );
          return;
        }
        if (result.tabularAnswer !== null) {
          /* The tabular engine answered: tables were selected, no document. Written here, in her
             language, from facts - except for a value the engine computed from a model-written
             plan (session 14's hidden interpreter, `docs/SESSION-DATA-14-Query-Plan.md`), where a
             model *did* spend real time and really was asked, even though it never wrote a word
             of the answer's text either: the number is still the engine's alone. That one case
             gets the same "generated by" treatment as an ordinary model answer, with its own
             duration, rather than the blanket "without the AI" line - which a manual validation
             pass (1 October 2026) found genuinely misleading after a real wait with a spinner. */
          const tabularAnswer = result.tabularAnswer;
          const previous = [...baseEntries].reverse().find((entry) => entry.role === "assistant");
          const nudge = tabularAnswer.kind === "nudge";
          const source = tabularSourceOf(tabularAnswer);
          const interpreted =
            tabularAnswer.kind === "value" && tabularAnswer.derivation.kind === "interpreted_by_model"
              ? tabularAnswer.derivation
              : null;
          // A nudge is still entirely deterministic text - no model wrote a word of it - but one
          // that followed a real, failed model attempt still cost real time, and that must not
          // vanish (`docs/DECISIONS.md`, the session 14 manual validation pass).
          const modelAttempt =
            tabularAnswer.kind === "nudge" || tabularAnswer.kind === "value"
              ? (tabularAnswer.modelAttempt ?? null)
              : null;
          const retryable = tabularAnswer.kind === "value" || tabularAnswer.kind === "nudge";
          setEntries((current) =>
            current.map((entry) =>
              entry.id === answerId
                ? {
                    ...entry,
                    content: formatTabularAnswer(
                      t,
                      tabularAnswer,
                      locale,
                      nudge && previous?.tabularNudge === true,
                    ),
                    tabular: true as const,
                    ...(interpreted === null
                      ? { deterministic: true as const }
                      : {
                          durationMs: performance.now() - startedAt,
                          modelAlias: interpreted.model_alias,
                        }),
                    ...(modelAttempt === null
                      ? {}
                      : {
                          modelAttemptAlias: modelAttempt.modelAlias,
                          modelAttemptDurationMs: modelAttempt.durationMs,
                          // A kept computed value: the line says so, instead of "could not turn
                          // this question into something computable" (HAP-1, BUG-18).
                          ...(tabularAnswer.kind === "value" ? { modelAttemptKept: true as const } : {}),
                        }),
                    ...(retryable ? { tabularRetryable: true as const } : {}),
                    ...(source === null ? {} : { tabularSource: source }),
                    ...(nudge ? { tabularNudge: true as const } : {}),
                    ...(result.documentsNotNeeded ? { documentsNotNeeded: true as const } : {}),
                  }
                : entry,
            ),
          );
          return;
        }
        if (result.folderAnswer !== null) {
          if (outdated !== undefined) {
            setEntries((current) =>
              current.map((entry) =>
                entry.id === answerId ? { ...entry, scopeOutdated: outdated } : entry,
              ),
            );
          }
          // The work folder answered it. No model wrote this, so it is not labelled with one:
          // "generated by cabinet-chat" on a file count would be a lie about where a fact
          // came from, which is exactly what this sprint exists to prevent.
          return;
        }
        const durationMs = performance.now() - startedAt;
        setEntries((current) =>
          current.map((entry) =>
            entry.id === answerId
              ? {
                  ...entry,
                  durationMs,
                  modelAlias,
                  /* Said on the answer itself, not only on the folder panel. By the time she
                     reads this she is looking at the conversation, and "three documents were
                     not part of this" is only useful next to the answer it qualifies. */
                  ...(outdated === undefined ? {} : { scopeOutdated: outdated }),
                  ...(result.unanalysedFiles > 0
                    ? { unanalysedFiles: result.unanalysedFiles }
                    : {}),
                  ...(result.withoutDocuments ? { withoutDocuments: true as const } : {}),
                }
              : entry,
          ),
        );
      } catch (raw: unknown) {
        const failure = normaliseError(raw);
        if (wasStopped(failure.code)) {
          // Her own stop, so no banner and no health re-check: nothing went wrong. What stays
          // depends on what she asked for, decided when she clicked.
          if (stopRequest.current === "keepPartialAnswer") {
            setEntries((current) =>
              current.map((entry) =>
                entry.id === answerId
                  ? { ...entry, interrupted: "stopped" as const, modelAlias }
                  : entry,
              ),
            );
          } else {
            discardTurn();
          }
        } else if (failure.code === SERVER_TIMEOUT) {
          // The AI went quiet, but what it had already written is not worthless - it is what she
          // was reading. Keeping it matches what a stop does with the same half-finished text,
          // and deleting it was the asymmetry that made a slow answer feel like lost work. The
          // banner still says what happened, and she can close it.
          setError(failure);
          setEntries((current) =>
            current.map((entry) =>
              entry.id === answerId
                ? { ...entry, interrupted: "timedOut" as const, modelAlias }
                : entry,
            ),
          );
          onFailure?.();
        } else if (failure.code === INSUFFICIENT_EVIDENCE && !(await indexHasAnything())) {
          // A work folder can be chosen and never analysed. Retrieval is right to refuse, but
          // "nothing in your documents answers this" reads as a verdict on the documents when
          // the truth is that none have been read yet. Say which it is. Rust answered without a
          // gateway call in this case, so nothing was spent finding out.
          setEntries((current) =>
            current.map((entry) =>
              entry.id === answerId
                ? { ...entry, content: t("chat.notIndexedYet"), needsIndexing: true as const }
                : entry,
            ),
          );
        } else {
          setError(failure);
          // Drop the half-written answer: an incomplete summary is worse than none.
          setEntries((current) => current.filter((entry) => entry.id !== answerId));
          onFailure?.();
        }
      } finally {
        setPhase("idle");
        setStreamingId(null);
      }
    },
    [phase, onFailure, hasWorkFolder, modelAlias, scope, t, locale],
  );

  const send = useCallback(
    (question: string) => {
      const text = question.trim();
      if (text.length === 0) {
        return Promise.resolve();
      }
      return runTurn(entries, text);
    },
    [runTurn, entries],
  );

  const resend = useCallback(
    (questionEntryId: string, text: string) => {
      const trimmed = text.trim();
      const base = truncateForResend(entries, questionEntryId);
      if (trimmed.length === 0 || base === null) {
        return Promise.resolve();
      }
      return runTurn(base, trimmed);
    },
    [runTurn, entries],
  );

  const regenerate = useCallback(
    (answerEntryId: string) => {
      const truncated = truncateForRegenerate(entries, answerEntryId);
      if (truncated === null) {
        return Promise.resolve();
      }
      // Regenerating an answer the work folder gave would produce the same answer, byte for
      // byte - it is computed, not written. On those the control means something else: ask the
      // model this time. The interface says so, and it is the same button either way.
      const wasDeterministic =
        entries.find((entry) => entry.id === answerEntryId)?.deterministic === true;
      return runTurn(truncated.base, truncated.question, wasDeterministic);
    },
    [runTurn, entries],
  );

  const stop = useCallback((): string | null => {
    const outcome = stopOutcome(phase);
    if (outcome === null) {
      return null;
    }
    stopRequest.current = outcome;
    // Rust ends the run with `chat_cancelled`, and the `catch` above applies the outcome. The
    // interface does not decide it is over on its own: that is how the request really stops, rather
    // than being hidden while the practice machine keeps writing into nothing.
    void cancelChat();
    return outcome === "discardTurn" ? asked.current : null;
  }, [phase]);

  const dismissError = useCallback(() => setError(null), []);

  const clear = useCallback(() => {
    if (phase !== "idle") {
      return;
    }
    setEntries([]);
    setError(null);
  }, [phase]);

  return {
    entries,
    phase,
    streamingId,
    error,
    send,
    resend,
    regenerate,
    stop,
    dismissError,
    clear,
  };
}
