import { useCallback, useRef, useState } from "react";
import { useTranslation } from "../i18n/I18nProvider";
import { normaliseError, type AppError } from "../lib/errors";
import {
  phaseAfterFirstText,
  stopOutcome,
  wasStopped,
  type GenerationPhase,
  type StopOutcome,
} from "../lib/generation";
import { formatFolderAnswer } from "../lib/folderAnswer";
import {
  askWithSources,
  cancelChat,
  hasIndexedDocuments,
  sendChatMessage,
  type ChatTurn,
  type Evidence,
  type EvidenceCoverage,
  type FolderAnswer,
} from "../lib/ipc";
import { truncateForRegenerate, truncateForResend } from "../lib/turns";

/** Retrieval found nothing to answer from. Either the documents do not carry it, or none have
 * been analysed yet, and the two deserve different sentences. */
const INSUFFICIENT_EVIDENCE = "insufficient_evidence";

/** The AI went quiet for longer than the configured wait. The answer it had already written is
 * real text she may have been reading, so it is kept, exactly as a stop keeps it. */
const SERVER_TIMEOUT = "server_timeout";

/** Whether the local index holds anything at all. Fails open: a transient index error must not
 * turn a real failure into "analyse your documents first". */
function indexHasAnything(): Promise<boolean> {
  return hasIndexedDocuments().catch(() => true);
}

export interface ChatEntry extends ChatTurn {
  id: string;
  /** When the turn was written, by the workstation clock. Shown above a question so a long
   * conversation can be read back in order; it never leaves the webview. */
  createdAt: number;
  /** Present on an assistant answer that came from the local index, so it can cite file and page. */
  sources?: Evidence[];
  /** Present when the question asked about every document. Shown so an answer that covered six
   * of ten analysed files cannot read as though it had covered all ten
   * (`docs/WORK-FOLDER-INVENTORY.md`). */
  coverage?: EvidenceCoverage;
  /** The work folder answered this itself: read from the disk and the local index, with no model
   * involved. Said on screen, because an answer with no model behind it is a different kind of
   * answer and the absence of a "generated by" line is too quiet a way to say so. */
  deterministic?: true;
  /** This answer stops mid-sentence, and why. Shown as such either way: an incomplete summary
   * that looks finished is the risk the disclaimer exists for. "stopped" is her own stop;
   * "timedOut" is the AI falling silent, and the two must not be confused - one was her
   * decision, the other was not. */
  interrupted?: "stopped" | "timedOut";
  /** How long the answer took to write, and which profile wrote it - shown so a slow machine is
   * visible rather than silently endured (`docs/HARDWARE.md`). */
  durationMs?: number;
  modelAlias?: string;
}

export interface ChatState {
  entries: ChatEntry[];
  /** "thinking" until the first words of the answer arrive, "writing" afterwards. Every stop
   * affordance and the spinner read this, so they cannot disagree about what is happening. */
  phase: GenerationPhase;
  /** The answer being written right now, so the spinner and the stop under it appear on that one
   * answer rather than under every answer already in the conversation. */
  streamingId: string | null;
  error: AppError | null;
  send: (question: string) => Promise<void>;
  /** Edited-and-reposted question (docs/CHAT-UX-ASSESSMENT.md item 3). Truncates `entries` to
   * before `questionEntryId` and asks the edited text as a fresh turn - not a rewrite of the old
   * one. No version history is kept: truncate and replace, per the recorded decision. */
  resend: (questionEntryId: string, text: string) => Promise<void>;
  /** Regenerate (item 4). Drops the answer at `answerEntryId` and the question right before it,
   * then asks that same question again. Retrieval, embedding and the model all run afresh, so the
   * sources shown are this run's own rather than the previous run's. */
  regenerate: (answerEntryId: string) => Promise<void>;
  /** Close the error banner. A failure that has already happened should not keep taking up the
   * conversation until the next question succeeds. */
  dismissError: () => void;
  /** Stops the question being worked on. Returns the question's text when stopping abandoned it
   * altogether, so the composer can offer it again - a stop before any answer is a question to
   * rephrase far more often than one to forget. Returns null when an answer was already being
   * written, since that text stays on screen and the composer is left as she had it. */
  stop: () => string | null;
}

/**
 * `onFailure` runs when a message could not be answered. The window uses it to re-ask the gateway
 * how it is, so a server that went down is reported by the indicator and not only by this banner.
 *
 * `hasWorkFolder` chooses the path: with a work folder chosen, every question goes through
 * retrieval first and is answered only from what the local index actually returns
 * (`docs/RETRIEVAL.md`). Without one, chat falls back to the plain conversation.
 */
export function useChat(
  onFailure?: () => void,
  hasWorkFolder = false,
  modelAlias?: string,
): ChatState {
  const { t } = useTranslation();
  const [entries, setEntries] = useState<ChatEntry[]>([]);
  const [phase, setPhase] = useState<GenerationPhase>("idle");
  const [streamingId, setStreamingId] = useState<string | null>(null);
  const [error, setError] = useState<AppError | null>(null);
  /** The question in flight, so stopping it can offer it back without reading it out of the list
   * that is about to lose it. */
  const asked = useRef("");
  /** What she asked a stop to leave behind, recorded when she clicked rather than worked out again
   * once the request has ended - by then the phase has moved on. Null means no stop was asked for. */
  const stopRequest = useRef<StopOutcome | null>(null);

  /**
   * The turn itself, shared by a fresh question, an edited repost and a regenerate: all three are
   * "append this question and its answer onto some prefix of the conversation", differing only in
   * what that prefix is. `baseEntries` is taken as a parameter rather than read from state so a
   * repost or regenerate can truncate first and send against the truncated list in the same tick -
   * the non-retrieval path below rebuilds its turns from it, and a stale `entries` closure would
   * resend the tail that was just cut.
   */
  const runTurn = useCallback(
    async (baseEntries: ChatEntry[], text: string, skipDeterministic = false) => {
      if (phase !== "idle") {
        return;
      }
      const questionId = crypto.randomUUID();
      const answerId = crypto.randomUUID();
      const createdAt = Date.now();
      asked.current = text;
      stopRequest.current = null;
      setError(null);
      setPhase("thinking");
      setStreamingId(answerId);
      setEntries([
        ...baseEntries,
        { id: questionId, role: "user", content: text, createdAt },
        { id: answerId, role: "assistant", content: "", createdAt },
      ]);

      const onDelta = (delta: string) => {
        setPhase(phaseAfterFirstText);
        setEntries((current) =>
          current.map((entry) => {
            if (entry.id !== answerId) {
              return entry;
            }
            // Ollama's chat template often opens an answer with a leading space token; strip
            // one only from the very first piece of a fresh answer, never mid-stream, so a
            // legitimate space inside the text is never touched.
            const piece = entry.content.length === 0 ? delta.replace(/^ /, "") : delta;
            return { ...entry, content: entry.content + piece };
          }),
        );
      };
      /* Sources arrive on their own event, before the first word of the answer, because retrieval
         has already finished by then. An answer she interrupts therefore still cites the documents
         it was written from, which an answer left on screen has to do. */
      const onSources = (sources: Evidence[], coverage: EvidenceCoverage | null) => {
        setEntries((current) =>
          current.map((entry) =>
            entry.id === answerId
              ? { ...entry, sources, ...(coverage === null ? {} : { coverage }) }
              : entry,
          ),
        );
      };
      /* A question the work folder answered by itself: no model wrote this, so it arrives as
         facts and machine codes and the sentence is written here, in her language. There are no
         sources because nothing was retrieved - the filesystem is the evidence
         (`docs/WORK-FOLDER-INVENTORY.md`). */
      const onFolderAnswer = (folderAnswer: FolderAnswer) => {
        const text = formatFolderAnswer(t, folderAnswer);
        setEntries((current) =>
          current.map((entry) =>
            entry.id === answerId
              ? { ...entry, content: text, deterministic: true as const }
              : entry,
          ),
        );
      };
      /* What a stop before any answer leaves behind: nothing at all, question included, so the
         conversation returns to exactly what it was. */
      const discardTurn = () =>
        setEntries((current) =>
          current.filter((entry) => entry.id !== questionId && entry.id !== answerId),
        );
      const startedAt = performance.now();

      try {
        if (hasWorkFolder) {
          const result = await askWithSources(
            text,
            onDelta,
            onSources,
            onFolderAnswer,
            skipDeterministic,
          );
          if (result.folderAnswer !== null) {
            // The work folder answered it. No model wrote this, so it is not labelled with one:
            // "generated by cabinet-chat" on a file count would be a lie about where a fact
            // came from, which is exactly what this sprint exists to prevent.
            return;
          }
          const durationMs = performance.now() - startedAt;
          setEntries((current) =>
            current.map((entry) =>
              entry.id === answerId ? { ...entry, durationMs, modelAlias } : entry,
            ),
          );
        } else {
          const turns: ChatTurn[] = [
            ...baseEntries.map(({ role, content }) => ({ role, content })),
            { role: "user", content: text },
          ];
          await sendChatMessage(turns, onDelta);
          const durationMs = performance.now() - startedAt;
          setEntries((current) =>
            current.map((entry) =>
              entry.id === answerId ? { ...entry, durationMs, modelAlias } : entry,
            ),
          );
        }
      } catch (raw: unknown) {
        const failure = normaliseError(raw);
        if (wasStopped(failure.code)) {
          // Her own stop, so no banner and no health re-check: nothing went wrong. What stays
          // depends on what she asked for, decided when she clicked.
          if (stopRequest.current === "keepPartialAnswer") {
            setEntries((current) =>
              current.map((entry) =>
                entry.id === answerId
                  ? { ...entry, interrupted: "stopped" as const, modelAlias }
                  : entry,
              ),
            );
          } else {
            discardTurn();
          }
        } else if (failure.code === SERVER_TIMEOUT) {
          // The AI went quiet, but what it had already written is not worthless - it is what she
          // was reading. Keeping it matches what a stop does with the same half-finished text,
          // and deleting it was the asymmetry that made a slow answer feel like lost work. The
          // banner still says what happened, and she can close it.
          setError(failure);
          setEntries((current) =>
            current.map((entry) =>
              entry.id === answerId
                ? { ...entry, interrupted: "timedOut" as const, modelAlias }
                : entry,
            ),
          );
          onFailure?.();
        } else if (failure.code === INSUFFICIENT_EVIDENCE && !(await indexHasAnything())) {
          // A work folder can be chosen and never analysed. Retrieval is right to refuse, but
          // "nothing in your documents answers this" reads as a verdict on the documents when
          // the truth is that none have been read yet. Say which it is. Rust answered without a
          // gateway call in this case, so nothing was spent finding out.
          setEntries((current) =>
            current.map((entry) =>
              entry.id === answerId ? { ...entry, content: t("chat.notIndexedYet") } : entry,
            ),
          );
        } else {
          setError(failure);
          // Drop the half-written answer: an incomplete summary is worse than none.
          setEntries((current) => current.filter((entry) => entry.id !== answerId));
          onFailure?.();
        }
      } finally {
        setPhase("idle");
        setStreamingId(null);
      }
    },
    [phase, onFailure, hasWorkFolder, modelAlias, t],
  );

  const send = useCallback(
    (question: string) => {
      const text = question.trim();
      if (text.length === 0) {
        return Promise.resolve();
      }
      return runTurn(entries, text);
    },
    [runTurn, entries],
  );

  const resend = useCallback(
    (questionEntryId: string, text: string) => {
      const trimmed = text.trim();
      const base = truncateForResend(entries, questionEntryId);
      if (trimmed.length === 0 || base === null) {
        return Promise.resolve();
      }
      return runTurn(base, trimmed);
    },
    [runTurn, entries],
  );

  const regenerate = useCallback(
    (answerEntryId: string) => {
      const truncated = truncateForRegenerate(entries, answerEntryId);
      if (truncated === null) {
        return Promise.resolve();
      }
      // Regenerating an answer the work folder gave would produce the same answer, byte for
      // byte - it is computed, not written. On those the control means something else: ask the
      // model this time. The interface says so, and it is the same button either way.
      const wasDeterministic =
        entries.find((entry) => entry.id === answerEntryId)?.deterministic === true;
      return runTurn(truncated.base, truncated.question, wasDeterministic);
    },
    [runTurn, entries],
  );

  const stop = useCallback((): string | null => {
    const outcome = stopOutcome(phase);
    if (outcome === null) {
      return null;
    }
    stopRequest.current = outcome;
    // Rust ends the run with `chat_cancelled`, and the `catch` above applies the outcome. The
    // interface does not decide it is over on its own: that is how the request really stops, rather
    // than being hidden while the practice machine keeps writing into nothing.
    void cancelChat();
    return outcome === "discardTurn" ? asked.current : null;
  }, [phase]);

  const dismissError = useCallback(() => setError(null), []);

  return {
    entries,
    phase,
    streamingId,
    error,
    send,
    resend,
    regenerate,
    stop,
    dismissError,
  };
}
