import { useEffect, useRef, useState } from "react";
import { useTranslation } from "../i18n/I18nProvider";
import { copyToClipboard } from "../lib/clipboard";
import { rewriteQuestion } from "../lib/choices";
import { localiseInternalNames } from "../lib/displayNames";
import { annotationLines } from "../lib/annotations";
import { groupSources } from "../lib/sourceGroups";
import { formatTabularAnswer, tabularSourceLine } from "../lib/tabularAnswer";
import type { GenerationPhase } from "../lib/generation";
import {
  isNearBottom,
  nextFollowing,
  prefersReducedMotion,
  SCROLL_KEYS,
  scrollBehaviour,
  USER_INTENT_WINDOW_MS,
} from "../lib/scroll";
import { timestampParts } from "../lib/timestamp";
import type { ChatEntry } from "../state/useChat";
import { ArrowDownGlyph } from "./ArrowDownGlyph";
import { CollapsibleText } from "./CollapsibleText";
import { Markdown } from "./Markdown";

export function MessageList({
  entries,
  phase,
  streamingId,
  onStop,
  onResend,
  onRegenerate,
  onAnalyse,
  analysing,
}: {
  entries: ChatEntry[];
  phase: GenerationPhase;
  streamingId: string | null;
  onStop: () => void;
  /** Edit-and-repost a past question (docs/CHAT-UX-ASSESSMENT.md item 3). */
  onResend: (questionEntryId: string, text: string) => void;
  /** Regenerate a past answer (item 4). */
  onRegenerate: (answerEntryId: string) => void;
  /** Analyse the folder, then ask this question again. Offered under the one answer that says the
   * documents have not been read yet, because that is the only thing that answer needs. */
  onAnalyse: (answerEntryId: string) => void;
  /** Whether the shared analysis pass is running, wherever it was started from. */
  analysing: boolean;
}) {
  const { t, locale } = useTranslation();
  const messages = useRef<HTMLDivElement>(null);
  const bottom = useRef<HTMLDivElement>(null);
  const turnCount = useRef(0);
  /* Whether a streaming answer may keep pulling the view down. Read from the scroll position as
     she scrolls, never after the text grew, so a delta that adds a line is not mistaken for her
     having scrolled away. */
  const following = useRef(true);
  /* When she last used the wheel, a finger, a scroll key or the scrollbar. A scroll event shortly
     after one is hers; any other is the content growing (HAP-1, BUG-08). */
  const lastIntent = useRef(0);
  const markIntent = () => {
    lastIntent.current = Date.now();
  };
  const [endVisible, setEndVisible] = useState(true);
  /* The one question being edited in place, or null. Editing is exclusive - only one turn's
     textarea exists at a time - so this is a single id rather than a set. */
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editDraft, setEditDraft] = useState("");
  /* Copy and edit change nothing about the conversation itself, so a generating turn does not
     block them; but resend and regenerate start a new request, which the existing "one question
     at a time" rule already enforces in `useChat` - here they are simply hidden while busy, since
     an answer already being written cannot be edited or regenerated. */
  const idle = phase === "idle";

  const startEdit = (entry: ChatEntry) => {
    setEditingId(entry.id);
    setEditDraft(entry.content);
  };
  const cancelEdit = () => {
    setEditingId(null);
    setEditDraft("");
  };
  const submitEdit = (questionEntryId: string) => {
    const text = editDraft.trim();
    if (text.length === 0) {
      return;
    }
    onResend(questionEntryId, text);
    cancelEdit();
  };

  const onScroll = () => {
    const root = messages.current;
    if (root === null) {
      return;
    }
    const atEnd = isNearBottom(root.scrollHeight, root.scrollTop, root.clientHeight);
    const causedByHer = Date.now() - lastIntent.current <= USER_INTENT_WINDOW_MS;
    following.current = nextFollowing(following.current, atEnd, causedByHer);
    setEndVisible(atEnd);
  };

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (SCROLL_KEYS.includes(event.key)) {
        markIntent();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  /* What an answer gains after its text - the "generated by" line, the sources, the buttons - and a
     deterministic answer arriving as one block make the list taller without any new delta. Each
     turn is observed, and the view follows the growth while she has not left the end. */
  useEffect(() => {
    const root = messages.current;
    if (root === null || typeof ResizeObserver === "undefined") {
      return undefined;
    }
    const observer = new ResizeObserver(() => {
      if (following.current) {
        bottom.current?.scrollIntoView({ block: "end" });
      }
    });
    for (const child of Array.from(root.children)) {
      observer.observe(child);
    }
    return () => observer.disconnect();
  }, [entries]);

  /* One more scroll the moment an answer is finished, whatever else changed in the same render. */
  useEffect(() => {
    if (phase === "idle" && following.current) {
      bottom.current?.scrollIntoView({ block: "end" });
    }
  }, [phase]);

  useEffect(() => {
    // A new turn is her own action, so it always scrolls. A delta of a streaming answer follows
    // only while she is at the bottom: `entries` is replaced on every delta, so an ungated effect
    // drags the view back down many times a second even though she is reading further up.
    const isNewTurn = entries.length !== turnCount.current;
    turnCount.current = entries.length;
    if (isNewTurn || following.current) {
      bottom.current?.scrollIntoView({ block: "end" });
    }
  }, [entries]);

  if (entries.length === 0) {
    return (
      <div className="messages messages--empty">
        <h2 className="empty__title">{t("chat.emptyTitle")}</h2>
        <p className="empty__body">{t("chat.emptyBody")}</p>
        <p className="empty__body">{t("chat.emptyBodyNetwork")}</p>
      </div>
    );
  }

  return (
    <div className="messages-pane">
      <div
        className="messages"
        ref={messages}
        onScroll={onScroll}
        onWheel={markIntent}
        onTouchMove={markIntent}
        onPointerDown={markIntent}
      >
        {entries.map((entry) => {
          if (entry.role === "user") {
            const editing = editingId === entry.id;
            return (
              <article
                key={entry.id}
                className={editing ? "message message--user message--editing" : "message message--user"}
              >
                <p className="message__timing message__timing--asked">
                  {t("chat.askedAt", timestampParts(entry.createdAt))}
                </p>
                {editing ? (
                  <div className="message__edit">
                    <textarea
                      className="message__edit-input"
                      value={editDraft}
                      rows={3}
                      autoFocus
                      onChange={(event) => setEditDraft(event.target.value)}
                    />
                    <p className="message__actions">
                      <button type="button" className="button" onClick={cancelEdit}>
                        {t("actions.cancel")}
                      </button>
                      <button
                        type="button"
                        className="button button--primary"
                        onClick={() => submitEdit(entry.id)}
                        disabled={editDraft.trim().length === 0}
                      >
                        {t("actions.send")}
                      </button>
                    </p>
                  </div>
                ) : (
                  <>
                    <div className="message__bubble">
                      <CollapsibleText text={entry.content} />
                    </div>
                    {idle ? (
                      <p className="message__actions message__actions--turn">
                        <button
                          type="button"
                          className="button button--compact"
                          onClick={() => void copyToClipboard(entry.content)}
                        >
                          {t("actions.copy")}
                        </button>
                        <button
                          type="button"
                          className="button button--compact"
                          onClick={() => startEdit(entry)}
                        >
                          {t("actions.edit")}
                        </button>
                      </p>
                    ) : null}
                  </>
                )}
              </article>
            );
          }
          // Both read the phase of the one answer being written, so a spinner, a stop and an
          // answer already finished further up can never be confused for one another.
          const streaming = entry.id === streamingId;
          const showPending = streaming && phase === "thinking";
          const showStop = streaming && phase === "writing";
          // What the user reads and copies: internal block names a model repeated are shown as the
          // names the application uses (BUG-10). The stored entry keeps the model's own words.
          const shown = localiseInternalNames(entry.content, t);
          // The question this "which file?" answer asked about, to be resent with her pick in it.
          const askedAbout = entries[entries.indexOf(entry) - 1];
          return (
            <article key={entry.id} className="message message--assistant">
              <p className="message__author">{t("chat.authorAssistant")}</p>
              {/* A div, not a paragraph: markdown emits lists and headings, which cannot legally
                  nest inside a `<p>` and make the browser restructure the DOM silently. */}
              <div className="message__body message__body--markdown">
                {showPending ? (
                  <span className="message__pending">
                    <span className="spinner" aria-hidden="true" />
                    {t("chat.pending")}
                    {/* The second way to stop, where she is already looking. It lives inside the
                        spinner line on purpose: it therefore exists exactly while the spinner
                        does, which is the rule itself rather than a copy of it. */}
                    <button
                      type="button"
                      className="button button--compact message__stop"
                      onClick={onStop}
                    >
                      {t("actions.stop")}
                    </button>
                  </span>
                ) : (
                  <Markdown text={shown} />
                )}
              </div>
              {/* Under the text, following its end as it grows, and gone the moment it stops
                  growing. Nothing caps how long an answer may be, so a model that falls into a
                  repetition loop has to be stoppable from where she is reading it. */}
              {showStop ? (
                <p className="message__actions">
                  {/* Discreet on purpose, styled like the copy/edit/regenerate row rather than
                      `button--primary`: a filled accent button reads as "the thing to do next",
                      which is wrong for a stop that most answers never need. */}
                  <button
                    type="button"
                    className="button button--compact message__stop"
                    onClick={onStop}
                  >
                    {t("actions.stop")}
                  </button>
                </p>
              ) : null}
              {entry.sources !== undefined && entry.sources.length > 0 ? (
                <details className="message__sources">
                  <summary className="disclosure">{t("chat.sourcesToggle")}</summary>
                  <ul className="message__sources-list">
                    {groupSources(entry.sources).map((group) => (
                      <li key={group.relativePath} className="message__source">
                        {t(group.pages.length > 1 ? "chat.sourceItemPages" : "chat.sourceItemPage", {
                          path: group.relativePath,
                          pages: group.pages.join(", "),
                        })}
                        {group.ocr ? t("chat.sourceOcrMarker") : null}
                      </li>
                    ))}
                  </ul>
                </details>
              ) : null}
              {/* The same disclosure for an answer the tabular engine computed: a workbook cites
                  the sheet (and column) its value came from, where a document cites its page. */}
              {entry.tabularSource === undefined ? null : (
                <details className="message__sources">
                  <summary className="disclosure">{t("chat.sourcesToggle")}</summary>
                  <ul className="message__sources-list">
                    <li className="message__source">{tabularSourceLine(t, entry.tabularSource)}</li>
                  </ul>
                </details>
              )}
              {/* A mixed answer's own table "based on" line, its own disclosure beside the document
                  sources' one above - two labelled groups, pages and sheets/columns, so she can
                  always tell which engine each fact came from (`docs/SESSION-DATA-16-Mixed-Tier.md`,
                  mechanism 5). */}
              {/* The figure the engine computed, shown beside the model's prose, always (HAP-1,
                  BUG-16): the prose may be wrong or terse, and the reader must have the number to check
                  it against, with the filters it was computed under. Not repeated when the table's
                  own sentence is already the whole answer. */}
              {entry.mixedTable?.kind === "value" && entry.deterministic !== true ? (
                <div className="message__computed">
                  <p className="message__timing">{t("chat.mixedComputedTitle")}</p>
                  <Markdown text={formatTabularAnswer(t, entry.mixedTable, locale)} />
                </div>
              ) : null}
              {entry.mixedTableSource === undefined ? null : (
                <details className="message__sources">
                  <summary className="disclosure">{t("chat.sourcesToggle")}</summary>
                  <ul className="message__sources-list">
                    <li className="message__source">{tabularSourceLine(t, entry.mixedTableSource)}</li>
                  </ul>
                </details>
              )}
              {/* Every note under the answer, as lines: where it came from, what it rests on, what could
                  not be established (`lib/annotations.ts`, also what "Copy the conversation" copies). */}
              {annotationLines(t, locale, entry).map((line, index) => (
                <p className="message__timing" key={`note-${index}`}>
                  {line}
                </p>
              ))}
              {/* A "which file?" answer offers its candidates as buttons. A click replaces her
                  question in place with one that names the file (the edit-and-resend path), so she
                  does not retype it (HAP-1, UX-1). */}
              {idle && entry.choices !== undefined && askedAbout?.role === "user" ? (
                <div className="message__choices">
                  <p className="message__timing">{t("choices.hint")}</p>
                  <p className="message__actions">
                    {entry.choices.map((choice) => (
                      <button
                        key={choice.path}
                        type="button"
                        className="button button--compact"
                        onClick={() => onResend(askedAbout.id, rewriteQuestion(t, askedAbout.content, choice))}
                      >
                        {choice.path}
                      </button>
                    ))}
                  </p>
                </div>
              ) : null}
              {/* An answer that says "analyse your documents first" is not text to keep or to
                  write again - it is a step she has not taken. Copy and regenerate would both
                  produce the same sentence, so the turn offers the step itself, and asks the
                  question again once the pass has run. */}
              {idle && entry.needsIndexing === true ? (
                <p className="message__actions message__actions--turn">
                  <button
                    type="button"
                    className="button button--compact"
                    disabled={analysing}
                    onClick={() => onAnalyse(entry.id)}
                  >
                    {analysing ? (
                      <span className="message__pending">
                        <span className="spinner" aria-hidden="true" />
                        {t("actions.analyzing")}
                      </span>
                    ) : (
                      t("actions.analyze")
                    )}
                  </button>
                </p>
              ) : idle && entry.content.length > 0 ? (
                <p className="message__actions message__actions--turn">
                  <button
                    type="button"
                    className="button button--compact"
                    onClick={() => void copyToClipboard(shown)}
                  >
                    {t("actions.copy")}
                  </button>
                  {/* Regenerating drops this answer and reruns retrieval, embedding and the model
                      from the question that produced it, so a new answer never keeps an old
                      answer's sources - a citation from the previous run would be worse than
                      none.

                      On an answer the work folder computed, rerunning would return the same
                      answer byte for byte, so the same control means "ask the model instead" and
                      says so. One button, two honest meanings, rather than a second button. */}
                  {/* A tabular answer that names a human choice instead of data (which column,
                      which workbook...) would come back byte for byte - asking the model would
                      not be a second opinion, it would be a guess this product refuses to make.
                      A computed value or a nudge is different: `tabularRetryable` marks exactly
                      those two, and the same control means "Demander a l'IA"/"Ask AI" for them,
                      found worth adding from a real wrong deterministic answer in a manual
                      validation pass (`docs/DECISIONS.md`, 1 October 2026). */}
                  {entry.tabular === true && entry.tabularRetryable !== true ? null : (
                    <button
                      type="button"
                      className="button button--compact"
                      onClick={() => onRegenerate(entry.id)}
                    >
                      {t(
                        entry.deterministic === true
                          ? "actions.regenerateWithModel"
                          : "actions.regenerate",
                      )}
                    </button>
                  )}
                </p>
              ) : null}
            </article>
          );
        })}
        <div ref={bottom} />
      </div>
      {endVisible ? null : (
        <button
          type="button"
          className="button messages-pane__to-bottom"
          aria-label={t("chat.scrollToBottom")}
          onClick={() =>
            bottom.current?.scrollIntoView({
              behavior: scrollBehaviour(prefersReducedMotion()),
              block: "end",
            })
          }
        >
          <ArrowDownGlyph />
        </button>
      )}
    </div>
  );
}
